features_type: spec
sr: 44100
sample_length_seconds: 2
frame_length: 440
hop_length: 110
min_freq: 0
max_freq: 2000
window_type: hann
mode: mel
normalize_audio: True
normalize_features: True
subtimesteps: True
n_mels: 21
